AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  text-analysis-service
  
  Serverless text analysis microservice for clustering and sentiment analysis.

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Runtime: python3.13
    Architectures:
      - x86_64
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Parameters:
  HoneycombApiKey:
    Type: String
    Default: replace-me
    Description: Honeycomb API Key for OpenTelemetry
  OtelServiceName:
    Type: String
    Default: text-analysis-service
    Description: Service name for OpenTelemetry
  OtelExporterEndpoint:
    Type: String
    Default: https://api.honeycomb.io
    Description: Exporter endpoint for OpenTelemetry

Resources:
  TextAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: functions/text_analysis/handler.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /analyze
            Method: POST
        HealthEvent:
          Type: Api
          Properties:
            Path: /health
            Method: GET
        OpenApiEvent:
          Type: Api
          Properties:
            Path: /openapi.json
            Method: GET
      Environment:
        Variables:
          LOG_LEVEL: INFO
          OTEL_SERVICE_NAME: !Ref OtelServiceName
          OTEL_EXPORTER_OTLP_ENDPOINT: !Ref OtelExporterEndpoint
          OTEL_EXPORTER_OTLP_HEADERS: !Sub "x-honeycomb-team=${HoneycombApiKey}"
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  TextAnalysisApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/analyze
  TextAnalysisFunction:
    Description: Text Analysis Lambda Function ARN
    Value: !GetAtt TextAnalysisFunction.Arn
  TextAnalysisFunctionIamRole:
    Description: Implicit IAM Role created for Text Analysis function
    Value: !GetAtt TextAnalysisFunctionRole.Arn